name: Build

on:
  push:
    branches: [ main, feat_cicd ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go get ./...
      - name: Build binary
        run: |
          ext=""
          if [ "${{ matrix.os }}" = "windows" ]; then ext=".exe"; fi
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o merge_frame${ext} main.go
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: merge_frame-${{ matrix.os }}-${{ matrix.arch }}
          path: merge_frame*